export function exportToCSV(data: any[], filename: string) {
  if (data.length === 0) {
    console.warn('No data to export')
    return
  }

  const headers = Object.keys(data[0])
  const csvContent = [
    headers.join(','),
    ...data.map(row => 
      headers.map(header => {
        const value = row[header]
        if (value === null || value === undefined) return ''
        if (typeof value === 'string' && value.includes(',')) {
          return `"${value}"`
        }
        return value
      }).join(',')
    )
  ].join('\n')

  downloadFile(csvContent, filename, 'text/csv')
}

export function exportToJSON(data: any, filename: string) {
  const jsonContent = JSON.stringify(data, null, 2)
  downloadFile(jsonContent, filename, 'application/json')
}

export function exportToHTML(content: string, filename: string) {
  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lotto Analyzer Report</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
      background: #f9fafb;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 2rem;
      border-radius: 0.5rem;
      margin-bottom: 2rem;
    }
    .content {
      background: white;
      padding: 2rem;
      border-radius: 0.5rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1rem 0;
    }
    th, td {
      padding: 0.75rem;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }
    th {
      background: #f3f4f6;
      font-weight: 600;
    }
    .footer {
      text-align: center;
      color: #6b7280;
      margin-top: 2rem;
      font-size: 0.875rem;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🎲 Lotto Analyzer Report</h1>
    <p>Generated on ${new Date().toLocaleString()}</p>
  </div>
  <div class="content">
    ${content}
  </div>
  <div class="footer">
    <p>Generated by Lotto Analyzer - Scientific Lottery Analysis Tool</p>
  </div>
</body>
</html>
  `
  downloadFile(htmlContent, filename, 'text/html')
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = window.URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  window.URL.revokeObjectURL(url)
}

export function formatDrawsForExport(draws: any[]) {
  return draws.map(draw => ({
    date: draw.draw_date,
    numbers: draw.numbers.join('-'),
    bonus: draw.bonus_numbers?.join('-') || 'N/A',
    sum: draw.numbers.reduce((a: number, b: number) => a + b, 0)
  }))
}

export function formatStatsForExport(stats: any) {
  return {
    summary: {
      totalDraws: stats.totalDraws,
      uniqueNumbers: stats.uniqueNumbers,
      avgFrequency: stats.avgFrequency,
      avgSum: stats.avgSum,
      minSum: stats.minSum,
      maxSum: stats.maxSum
    },
    mostFrequent: stats.mostFrequent.map(([num, count]: [string, number]) => ({
      number: num,
      frequency: count
    })),
    leastFrequent: stats.leastFrequent.map(([num, count]: [string, number]) => ({
      number: num,
      frequency: count
    })),
    evenOdd: stats.evenOdd,
    consecutivePairs: stats.consecutivePairs.map(([pair, count]: [string, number]) => ({
      pair,
      occurrences: count
    }))
  }
}
